name: Pack

on: [push, pull_request]

jobs:

  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 18
          cache: npm
      - run: node --version; npm --version
      - run: npm ci
      - name: Update clash's Country.mmdb
        run: rm package/clash/Country.mmdb && wget -O package/clash/Country.mmdb https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb
      - run: npm run pack
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cliesh.asar
          path: cliesh.asar